In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.drop(columns=['id','Unnamed: 32' ], inplace = True)
df

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0           M        17.99         10.38          122.80     1001.0   
1           M        20.57         17.77          132.90     1326.0   
2           M        19.69         21.25          130.00     1203.0   
3           M        11.42         20.38           77.58      386.1   
4           M        20.29         14.34          135.10     1297.0   
..        ...          ...           ...             ...        ...   
564         M        21.56         22.39          142.00     1479.0   
565         M        20.13         28.25          131.20     1261.0   
566         M        16.60         28.08          108.30      858.1   
567         M        20.60         29.33          140.10     1265.0   
568         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0           0.2419  ...        25.380          17.33           184.60   
1           0.1812  ...        24.990          23.41           158.80   
2           0.2069  ...        23.570          25.53           152.50   
3           0.2597  ...        14.910          26.50            98.87   
4           0.1809  ...        22.540          16.67           152.20   
..             ...  ...           ...            ...              ...   
564         0.1726  ...        25.450          26.40           166.10   
565         0.1752  ...        23.690          38.25           155.00   
566         0.1590  ...        18.980          34.12           126.70   
567         0.2397  ...        25.740          39.42           184.60   
568         0.1587  ...         9.456          30.37            59.16   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0        2019.0           0.16220            0.66560           0.7119   
1        1956.0           0.12380            0.18660           0.2416   
2        1709.0           0.14440            0.42450           0.4504   
3         567.7           0.20980            0.86630           0.6869   
4        1575.0           0.13740            0.20500           0.4000   
..          ...               ...                ...              ...   
564      2027.0           0.14100            0.21130           0.4107   
565      1731.0           0.11660            0.19220           0.3215   
566      1124.0           0.11390            0.30940           0.3403   
567      1821.0           0.16500            0.86810           0.9387   
568       268.6           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    ...         

In [4]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0], test_size=0.2)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((455, 30), (114, 30), (455,), (114,))

In [5]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [6]:
encoder  = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [7]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)


### Model Creation 

In [30]:
class MySimpleNN(nn.Module): # Use OOPs concept --> build a class 
    
    def __init__(self,num_features ): # Build a constructor 

        super().__init__() # inheritence 
        self.linear= nn.Linear(num_features, 1)
        # self.relu = nn.ReLU()
        # self.linear2 = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):

        out = self.linear(features)
        # out = self.relu(out)
        # out = self.linear2(out)
        out = self.sigmoid(out)

        return out

    def loss_function(self, y_pred, y):
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss


In [31]:
learning_rate  = 0.1
epochs  = 25

### training pipeline 

In [36]:
X_train_tensor = X_train_tensor.float()
y_train_tensor = y_train_tensor.float()  # Or `.long()` if these are class labels


In [38]:
#create model 
model = MySimpleNN(X_train_tensor.shape[1])

# Create a dataset

#features  = torch.rand(X_train_tensor.shape[1])


## Define Loop

for epoch in range(epochs):
    

## Forward Pass 
    y_pred = model(X_train_tensor)
    #print(y_pred)

## Loss Calculate 
    loss = model.loss_function(y_pred, y_train_tensor)
    #print(f"Epoch: {epoch + 1}, Loss: {loss.item()}")


## Backward Pass 
    loss.backward()

## Parameters Update
    with torch.no_grad(): # For not tracking the gradient 
        model.linear.weight -= learning_rate * model.linear.weight.grad
        model.linear.bias -= learning_rate * model.linear.bias.grad

## Zero gradients 
    model.linear.weight.grad.zero_()
    model.linear.bias.grad.zero_()

## Print Loss in each epoch
    print(f"Epoch: {epoch + 1}, Loss: {loss.item()}")

    


Epoch: 1, Loss: 0.7530511617660522
Epoch: 2, Loss: 0.7372019290924072
Epoch: 3, Loss: 0.7272571325302124
Epoch: 4, Loss: 0.7206013798713684
Epoch: 5, Loss: 0.7157236337661743
Epoch: 6, Loss: 0.7118204236030579
Epoch: 7, Loss: 0.7084826827049255
Epoch: 8, Loss: 0.70550537109375
Epoch: 9, Loss: 0.7027836441993713
Epoch: 10, Loss: 0.7002617716789246
Epoch: 11, Loss: 0.6979078650474548
Epoch: 12, Loss: 0.695701539516449
Epoch: 13, Loss: 0.6936283111572266
Epoch: 14, Loss: 0.6916771531105042
Epoch: 15, Loss: 0.6898388862609863
Epoch: 16, Loss: 0.6881054043769836
Epoch: 17, Loss: 0.6864696145057678
Epoch: 18, Loss: 0.6849251985549927
Epoch: 19, Loss: 0.683466374874115
Epoch: 20, Loss: 0.6820876002311707
Epoch: 21, Loss: 0.6807841062545776
Epoch: 22, Loss: 0.6795512437820435
Epoch: 23, Loss: 0.6783847212791443
Epoch: 24, Loss: 0.677280604839325
Epoch: 25, Loss: 0.6762353777885437


### Evaluation

In [40]:
# Ensure data types match
X_test_tensor = X_test_tensor.float()
y_test_tensor = y_test_tensor.float()

# Evaluation with no gradient tracking
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.9).float()
    accuracy = (y_pred == y_test_tensor).float().mean()

print(f'Accuracy: {accuracy.item():.4f}')


Accuracy: 0.5877


In [42]:
loss_function = nn.BCELoss()

In [44]:
#create model 
model = MySimpleNN(X_train_tensor.shape[1])

# Create a dataset

#features  = torch.rand(X_train_tensor.shape[1])


## Define Loop

for epoch in range(epochs):
    

## Forward Pass 
    y_pred = model(X_train_tensor)
    #print(y_pred)

## Loss Calculate 
    loss = loss_function(y_pred, y_train_tensor.view(-1,1))
    #print(f"Epoch: {epoch + 1}, Loss: {loss.item()}")


## Backward Pass 
    loss.backward()

## Parameters Update
    with torch.no_grad(): # For not tracking the gradient 
        model.linear.weight -= learning_rate * model.linear.weight.grad
        model.linear.bias -= learning_rate * model.linear.bias.grad

## Zero gradients 
    model.linear.weight.grad.zero_()
    model.linear.bias.grad.zero_()

## Print Loss in each epoch
    print(f"Epoch: {epoch + 1}, Loss: {loss.item()}")

    


Epoch: 1, Loss: 0.6840866208076477
Epoch: 2, Loss: 0.5005855560302734
Epoch: 3, Loss: 0.40979334712028503
Epoch: 4, Loss: 0.35669469833374023
Epoch: 5, Loss: 0.32124802470207214
Epoch: 6, Loss: 0.29550155997276306
Epoch: 7, Loss: 0.27571284770965576
Epoch: 8, Loss: 0.25987812876701355
Epoch: 9, Loss: 0.2468208521604538
Epoch: 10, Loss: 0.23580089211463928
Epoch: 11, Loss: 0.22632746398448944
Epoch: 12, Loss: 0.21806104481220245
Epoch: 13, Loss: 0.21075864136219025
Epoch: 14, Loss: 0.20424117147922516
Epoch: 15, Loss: 0.19837351143360138
Epoch: 16, Loss: 0.19305148720741272
Epoch: 17, Loss: 0.18819338083267212
Epoch: 18, Loss: 0.18373402953147888
Epoch: 19, Loss: 0.17962072789669037
Epoch: 20, Loss: 0.1758103370666504
Epoch: 21, Loss: 0.1722671240568161
Epoch: 22, Loss: 0.16896119713783264
Epoch: 23, Loss: 0.16586729884147644
Epoch: 24, Loss: 0.1629638969898224
Epoch: 25, Loss: 0.16023263335227966


In [45]:
# Ensure data types match
X_test_tensor = X_test_tensor.float()
y_test_tensor = y_test_tensor.float()

# Evaluation with no gradient tracking
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.9).float()
    accuracy = (y_pred == y_test_tensor).float().mean()

print(f'Accuracy: {accuracy.item():.4f}')


Accuracy: 0.5508


### Using torch.optim module 

In [46]:
#create model 
model = MySimpleNN(X_train_tensor.shape[1])

# Create a dataset

#features  = torch.rand(X_train_tensor.shape[1])


## Define Loop

for epoch in range(epochs):
    

## Forward Pass 
    y_pred = model(X_train_tensor)
    #print(y_pred)

## Loss Calculate 
    loss = loss_function(y_pred, y_train_tensor.view(-1,1))
    #print(f"Epoch: {epoch + 1}, Loss: {loss.item()}")


## Backward Pass 
    loss.backward()

## Parameters Update
    with torch.no_grad(): # For not tracking the gradient 
        model.linear.weight -= learning_rate * model.linear.weight.grad
        model.linear.bias -= learning_rate * model.linear.bias.grad

## Zero gradients 
    model.linear.weight.grad.zero_()
    model.linear.bias.grad.zero_()

## Print Loss in each epoch
    print(f"Epoch: {epoch + 1}, Loss: {loss.item()}")

    


Epoch: 1, Loss: 0.6606369018554688
Epoch: 2, Loss: 0.5153759717941284
Epoch: 3, Loss: 0.43435853719711304
Epoch: 4, Loss: 0.38245877623558044
Epoch: 5, Loss: 0.34592312574386597
Epoch: 6, Loss: 0.3185068368911743
Epoch: 7, Loss: 0.29698091745376587
Epoch: 8, Loss: 0.2795051634311676
Epoch: 9, Loss: 0.2649506628513336
Epoch: 10, Loss: 0.2525838315486908
Epoch: 11, Loss: 0.24190565943717957
Epoch: 12, Loss: 0.23256367444992065
Epoch: 13, Loss: 0.22430109977722168
Epoch: 14, Loss: 0.21692585945129395
Epoch: 15, Loss: 0.21029092371463776
Epoch: 16, Loss: 0.20428170263767242
Epoch: 17, Loss: 0.19880716502666473
Epoch: 18, Loss: 0.19379399716854095
Epoch: 19, Loss: 0.18918243050575256
Epoch: 20, Loss: 0.184922993183136
Epoch: 21, Loss: 0.18097445368766785
Epoch: 22, Loss: 0.1773020476102829
Epoch: 23, Loss: 0.17387616634368896
Epoch: 24, Loss: 0.17067156732082367
Epoch: 25, Loss: 0.16766633093357086


In [47]:
#create model 
model = MySimpleNN(X_train_tensor.shape[1])

# Define optimizer 
optimizer  = torch.optim.SGD(model.parameters(), lr=learning_rate)

## Define Loop

for epoch in range(epochs):
    

## Forward Pass 
    y_pred = model(X_train_tensor)
    #print(y_pred)

## Loss Calculate 
    loss = loss_function(y_pred, y_train_tensor.view(-1,1))
    #print(f"Epoch: {epoch + 1}, Loss: {loss.item()}")

## Clear gradients 
    optimizer.zero_grad()

## Backward Pass 
    loss.backward()

## Parameters Update
    optimizer.step()


## Zero gradients 
    model.linear.weight.grad.zero_()
    model.linear.bias.grad.zero_()

## Print Loss in each epoch
    print(f"Epoch: {epoch + 1}, Loss: {loss.item()}")


Epoch: 1, Loss: 0.7244612574577332
Epoch: 2, Loss: 0.5441065430641174
Epoch: 3, Loss: 0.4490414261817932
Epoch: 4, Loss: 0.3906572759151459
Epoch: 5, Loss: 0.3506012260913849
Epoch: 6, Loss: 0.3210628032684326
Epoch: 7, Loss: 0.2981717586517334
Epoch: 8, Loss: 0.2797824442386627
Epoch: 9, Loss: 0.2646034359931946
Epoch: 10, Loss: 0.25180670619010925
Epoch: 11, Loss: 0.24083493649959564
Epoch: 12, Loss: 0.23129744827747345
Epoch: 13, Loss: 0.22291147708892822
Epoch: 14, Loss: 0.2154664546251297
Epoch: 15, Loss: 0.20880204439163208
Epoch: 16, Loss: 0.20279358327388763
Epoch: 17, Loss: 0.19734252989292145
Epoch: 18, Loss: 0.1923697292804718
Epoch: 19, Loss: 0.18781088292598724
Epoch: 20, Loss: 0.18361300230026245
Epoch: 21, Loss: 0.1797320693731308
Epoch: 22, Loss: 0.17613114416599274
Epoch: 23, Loss: 0.1727789342403412
Epoch: 24, Loss: 0.16964882612228394
Epoch: 25, Loss: 0.16671791672706604


In [48]:
# Ensure data types match
X_test_tensor = X_test_tensor.float()
y_test_tensor = y_test_tensor.float()

# Evaluation with no gradient tracking
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.9).float()
    accuracy = (y_pred == y_test_tensor).float().mean()

print(f'Accuracy: {accuracy.item():.4f}')



Accuracy: 0.5523


In [12]:
# Create model class using nn.module 

import torch 
import torch.nn as nn

class Model(nn.Module):

    def __init__(self, num_features):

        super().__init__() # inheritence 
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):

        out = self.linear(features)
        out = self.sigmoid(out)

        return out


In [13]:
# Create a dataset

features  = torch.rand(10, 5)

# create a model 

model = Model(features.shape[1])

# call model for forward pass 

#model.forward(features) # No need to write like this 

model(features)

tensor([[0.7359],
        [0.6470],
        [0.6143],
        [0.7230],
        [0.7471],
        [0.6886],
        [0.6745],
        [0.6984],
        [0.6488],
        [0.6454]], grad_fn=<SigmoidBackward0>)

In [15]:
# Show model weights 

model.linear.weight

Parameter containing:
tensor([[ 0.1135, -0.0586,  0.0792,  0.4294,  0.4313]], requires_grad=True)

In [16]:
model.linear.bias

Parameter containing:
tensor([0.3260], requires_grad=True)

In [17]:
!pip install torchinfo 

In [18]:
from torchinfo import summary 
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

#### Here, trainable parameters 6 because no of features = 5 and 1 bias 

### Lets Increase the complexity ittle bit 
### Lets add a hidden layer 

In [19]:
# Create model class using nn.module 

import torch 
import torch.nn as nn

class Model(nn.Module):

    def __init__(self, num_features):

        super().__init__() # inheritence 
        self.linear1 = nn.Linear(num_features, 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):

        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)

        return out


In [20]:
# Create a dataset

features  = torch.rand(10, 5)

# create a model 

model = Model(features.shape[1])

# call model for forward pass 

#model.forward(features) # No need to write like this 

model(features)

tensor([[0.3244],
        [0.3279],
        [0.3367],
        [0.3536],
        [0.3524],
        [0.3469],
        [0.3392],
        [0.3544],
        [0.3477],
        [0.3362]], grad_fn=<SigmoidBackward0>)

In [21]:
model.linear1.weight

Parameter containing:
tensor([[ 0.4063, -0.1505,  0.1038,  0.4425, -0.0160],
        [-0.2924,  0.4081,  0.0107,  0.2901, -0.1196],
        [ 0.3687,  0.1330, -0.2489,  0.1847,  0.2924]], requires_grad=True)

In [23]:
model.linear2.weight

Parameter containing:
tensor([[-0.1650, -0.0895, -0.0805]], requires_grad=True)

In [24]:
from torchinfo import summary 
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

### Using Sequential container (to stack layers in order)

In [27]:
# Create model class using nn.module 

import torch 
import torch.nn as nn

class Model(nn.Module):

    def __init__(self, num_features):

        super().__init__() 
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )

    def forward(self, features):

        out = self.network(features)

        return out


In [28]:
# Create a dataset

features  = torch.rand(10, 5)

# create a model 

model = Model(features.shape[1])

# call model for forward pass 

#model.forward(features) # No need to write like this 

model(features)

tensor([[0.6248],
        [0.6092],
        [0.6172],
        [0.6023],
        [0.6154],
        [0.6023],
        [0.6312],
        [0.6023],
        [0.6105],
        [0.6023]], grad_fn=<SigmoidBackward0>)

In [29]:
from torchinfo import summary 
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00