In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [6]:
df.drop(columns=['id','Unnamed: 32' ], inplace = True)

In [7]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

### Train Test split  

In [29]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0], test_size=0.2)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((455, 30), (114, 30), (455,), (114,))

### Scaling 

In [30]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [13]:
X_train

array([[-0.1458721 ,  0.94216057, -0.19694756, ..., -0.6357702 ,
        -0.39982377, -0.78434407],
       [-0.48022764, -1.03045157, -0.5433418 , ..., -1.10948085,
         0.03414046, -0.87879186],
       [-0.502518  ,  0.69889583, -0.49328016, ..., -0.48100247,
        -1.02647482,  0.39847568],
       ...,
       [-0.93160761,  0.64109034, -0.93979768, ..., -0.58858122,
         0.14137486, -0.3904412 ],
       [-1.03191428, -0.92929197, -1.02740554, ..., -1.04696682,
        -0.44506329, -0.05320702],
       [ 0.92685193,  1.29140204,  0.97021531, ...,  0.88702289,
        -1.20743288,  0.51959108]])

In [14]:
y_train


545    B
241    B
163    B
30     M
248    B
      ..
271    B
82     M
427    B
226    B
168    M
Name: diagnosis, Length: 455, dtype: object

### Label Encoding 

In [31]:
encoder  = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [32]:
y_train

array([0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [33]:
X_train.dtype, X_test.dtype

(dtype('float64'), dtype('float64'))

### Numpy arrays to Pytorch Tensors

In [34]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)


In [35]:
X_train_tensor.shape

torch.Size([455, 30])

In [36]:
X_train_tensor

tensor([[-0.4149, -0.3493, -0.4705,  ..., -1.2265, -1.1909, -1.3323],
        [ 0.1286, -0.8071,  0.0167,  ..., -0.8890, -0.6073, -1.5118],
        [ 0.8390,  1.8430,  0.7879,  ...,  0.6044,  0.1602,  0.3177],
        ...,
        [-0.7140, -0.6961, -0.6991,  ..., -0.2752, -0.1692, -0.2456],
        [-1.0332,  0.2404, -0.9215,  ...,  0.4663, -0.5002,  1.9161],
        [ 1.8254,  1.9956,  1.7540,  ...,  0.6166, -0.7560, -0.0803]],
       dtype=torch.float64)

### Defining the model 


In [52]:
class MySimpleNN(): # Use OOPs concept --> build a class 
    def __init__(self, X): # Build a constructor 

        self.weights = torch.rand(X.shape[1], 1, dtype = torch.float64, requires_grad= True )
        self.bias = torch.zeros(1, dtype = torch.float64, requires_grad= True )


    def forward(self, X):
        z = torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    
    def loss_function(self, y_pred, y):
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss

### Important Parameters 


In [44]:
learning_rate  = 0.1
epochs  = 25


### Training Pipeline 

In [47]:
## Create Model 

model = MySimpleNN(X_train_tensor)
model.weights, model.bias 

(tensor([[0.9726],
         [0.9890],
         [0.4696],
         [0.3457],
         [0.3165],
         [0.8551],
         [0.2953],
         [0.9959],
         [0.5064],
         [0.3984],
         [0.1079],
         [0.0341],
         [0.4210],
         [0.1048],
         [0.6423],
         [0.3580],
         [0.9386],
         [0.8082],
         [0.6590],
         [0.0251],
         [0.3733],
         [0.1140],
         [0.5877],
         [0.7705],
         [0.7114],
         [0.7517],
         [0.9811],
         [0.2845],
         [0.2873],
         [0.6802]], dtype=torch.float64, requires_grad=True),
 tensor([0.], dtype=torch.float64, requires_grad=True))

In [57]:
## Create Model 

model = MySimpleNN(X_train_tensor)


## Define Loop

for epoch in range(epochs):
    

## Forward Pass 
    y_pred = model.forward(X_train_tensor)
    #print(y_pred)

## Loss Calculate 
    loss = model.loss_function(y_pred, y_train_tensor)
    #print(f"Epoch: {epoch + 1}, Loss: {loss.item()}")


## Backward Pass 
    loss.backward()

## Parameters Update
    with torch.no_grad(): # For not tracking the gradient 
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

## Zero gradients 
    model.weights.grad.zero_()
    model.bias.grad.zero_()

## Print Loss in each epoch
    print(f"Epoch: {epoch + 1}, Loss: {loss.item()}")

    


Epoch: 1, Loss: 3.4819101556628254
Epoch: 2, Loss: 3.3526024337955143
Epoch: 3, Loss: 3.220137009792009
Epoch: 4, Loss: 3.086190089094767
Epoch: 5, Loss: 2.950586998106731
Epoch: 6, Loss: 2.804067790548777
Epoch: 7, Loss: 2.6514403405379983
Epoch: 8, Loss: 2.497640861746134
Epoch: 9, Loss: 2.346148013320239
Epoch: 10, Loss: 2.195977173947955
Epoch: 11, Loss: 2.0454259459281916
Epoch: 12, Loss: 1.898205378341259
Epoch: 13, Loss: 1.7561530771888911
Epoch: 14, Loss: 1.6211155855493589
Epoch: 15, Loss: 1.4891450257392624
Epoch: 16, Loss: 1.3664957971353269
Epoch: 17, Loss: 1.2577074504658923
Epoch: 18, Loss: 1.1636184255265922
Epoch: 19, Loss: 1.084520880432012
Epoch: 20, Loss: 1.019973210891787
Epoch: 21, Loss: 0.9687209030439305
Epoch: 22, Loss: 0.9288231090138199
Epoch: 23, Loss: 0.8979879999641702
Epoch: 24, Loss: 0.8739775680437358
Epoch: 25, Loss: 0.8548994865851153


In [58]:
model.weights

tensor([[ 0.0200],
        [ 0.4545],
        [-0.0924],
        [ 0.4513],
        [-0.1558],
        [-0.0188],
        [-0.4242],
        [-0.5003],
        [ 0.1879],
        [ 0.3650],
        [ 0.2160],
        [ 0.5768],
        [ 0.4397],
        [-0.1566],
        [ 0.0169],
        [ 0.2461],
        [ 0.1976],
        [-0.2517],
        [ 0.1310],
        [-0.3113],
        [ 0.0506],
        [-0.0743],
        [-0.0007],
        [ 0.3489],
        [ 0.4405],
        [-0.0514],
        [-0.1740],
        [-0.4649],
        [ 0.2934],
        [ 0.2158]], dtype=torch.float64, requires_grad=True)

In [59]:
model.bias

tensor([-0.1395], dtype=torch.float64, requires_grad=True)

### Model Evaluation

In [62]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.9).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')


#print(y_train_tensor)


Accuracy: 0.6305016875267029


In [63]:
### Note: Very poor accuracy, but our target is to build training pipeline 