In [1]:
import torch 

In [2]:
print(torch.__version__)

2.6.0+cu124


In [3]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU is not available. Using CPU")

GPU is available
Using GPU: NVIDIA GeForce RTX 4050 Laptop GPU


### Creating a Tensor

In [7]:
a = torch.empty(2,3) 
## This empty function shows the value allocated already at particular memory space. It does not create any new value

In [9]:
type(a)

torch.Tensor

In [10]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [13]:
#Using Rand

torch.rand(2,3)

tensor([[0.3693, 0.0579, 0.3001],
        [0.6070, 0.3524, 0.9699]])

In [20]:
# Using Seed (It is important for reproducibility - because rand function will create different values at different time. So, we can't get same or access values at different times. So, we have to use seed along with rand )

torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [21]:
# Using Tensor

torch.tensor([[1,2,3],[5,6,7]])

tensor([[1, 2, 3],
        [5, 6, 7]])

In [22]:
# Using arange 

torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [23]:
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [26]:
torch.eye(10) #Identity matrix

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [28]:
torch.full((3,4),5)

tensor([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]])

### Tensor Shapes

In [29]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [30]:
x.shape

torch.Size([2, 3])

In [31]:
torch.empty_like(x)

tensor([[                  0, 7235419174270214779, 7162193695656131106],
        [3702351613448501043, 3761127335515010613, 7292788375037688166]])

In [32]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [33]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [35]:
torch.rand_like(x) # This code is not working because in x, all values are integers - but in rand function generally float values are created. So, we have to explicitly mention about their float values 


RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [44]:
#Solution

torch.rand_like(x, dtype=torch.float64)

tensor([[0.7911, 0.4274, 0.4460],
        [0.5522, 0.9559, 0.9405]], dtype=torch.float64)

### Tensor data types 

In [37]:
x.dtype

torch.int64

In [38]:
## Assign datatype 

torch.tensor([1.0, 2.0, 3.0], dtype = torch.int32)

/tmp/ipykernel_7048/2964232404.py:3: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  torch.tensor([1.0, 2.0, 3.0], dtype = torch.int32)


tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1, 2, 3], dtype = torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [41]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [42]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

### Mathematical Operations 

In [45]:
x = torch.rand(2,2)

In [46]:
x

tensor([[0.5277, 0.2472],
        [0.7909, 0.4235]])

In [47]:
# Addition 

x +2

tensor([[2.5277, 2.2472],
        [2.7909, 2.4235]])

In [48]:
# Subtraction 

x - 2

tensor([[-1.4723, -1.7528],
        [-1.2091, -1.5765]])

In [49]:
# Multiplication  

x * 2

tensor([[1.0554, 0.4944],
        [1.5818, 0.8470]])

In [50]:
# Division  

x / 2

tensor([[0.2638, 0.1236],
        [0.3954, 0.2117]])

In [52]:
# Int division 

(x * 100)//3

tensor([[17.,  8.],
        [26., 14.]])

In [53]:
# Mod

((x * 100)//3)%2

tensor([[1., 0.],
        [0., 0.]])

In [54]:
# Power 

x ** 2


tensor([[0.2785, 0.0611],
        [0.6255, 0.1793]])

### Element Wise operation 

In [58]:
a = torch.rand(2,3)
b = torch.rand(2,3)

In [59]:
print(a)
print(b)

tensor([[0.3290, 0.5301, 0.6401],
        [0.7954, 0.3066, 0.2397]])
tensor([[0.1156, 0.4839, 0.3944],
        [0.0801, 0.7782, 0.6686]])


In [60]:
# Addition

a + b 

tensor([[0.4446, 1.0141, 1.0345],
        [0.8755, 1.0849, 0.9082]])

In [61]:
# Subtraction 

a - b

tensor([[ 0.2134,  0.0462,  0.2457],
        [ 0.7153, -0.4716, -0.4289]])

In [62]:
# Multiplication 

a * b

tensor([[0.0380, 0.2566, 0.2524],
        [0.0637, 0.2386, 0.1602]])

In [63]:
# Division 

a / b

tensor([[2.8459, 1.0955, 1.6228],
        [9.9294, 0.3940, 0.3585]])

In [64]:
# Mod

a % b

tensor([[0.0978, 0.0462, 0.2457],
        [0.0745, 0.3066, 0.2397]])

In [65]:
c = torch.tensor([1, -2, 3, -4])

In [67]:
torch.abs(c)  # Getting the absolute values 

tensor([1, 2, 3, 4])

In [69]:
torch.neg(c) # negative values of all elements 


tensor([-1,  2, -3,  4])

In [70]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])


In [71]:
# round 
torch.round(d)

tensor([2., 2., 4., 4.])

In [73]:
# Ceil (Ceiling function) 
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [74]:
# Floor 

torch.floor(d)

tensor([1., 2., 3., 4.])

In [78]:
## Clamp  
torch.clamp(d, min=2, max = 3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### Reduction operation

In [80]:
e = torch.randint(size = (2,3), low=0, high=10)
e

tensor([[1, 0, 9],
        [6, 7, 8]])

In [83]:
## Sum 

torch.sum(e)

tensor(31)

In [82]:
# Sum along columns 

torch.sum(e, dim= 0 )

tensor([ 7,  7, 17])

In [84]:
# Sum along rows 

torch.sum(e, dim=1)

tensor([10, 21])

In [85]:
## mean 

torch.mean(e)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [86]:
# Solution: 

e = torch.randint(size = (2,3), low=0, high=10, dtype = torch.float32)

In [87]:
torch.mean(e)

tensor(4.5000)

In [88]:
# Mean along columns 

torch.mean(e, dim= 0)

tensor([6.0000, 2.0000, 5.5000])

In [89]:
# Mean along rows

torch.mean(e, dim= 1)

tensor([4., 5.])

In [90]:
## Median 

torch.median(e)

tensor(3.)

In [94]:
torch.max(e)


tensor(9.)

In [95]:
torch.min(e)

tensor(0.)

In [96]:
## Product 

torch.prod(e)

tensor(0.)

In [ ]:
# Standard Deviation

torch.std(e)

tensor(3.3912)

In [99]:
# Variance 

torch.var(e)

tensor(11.5000)

In [101]:
e

tensor([[9., 0., 3.],
        [3., 4., 8.]])

In [100]:
# ARGMAX

torch.argmax(e)

tensor(0)

In [102]:
# ARGMIN

torch.argmin(e)

tensor(1)

### Matrix operations 


In [104]:
f = torch.randint(size=(2,3),low= 0, high=10)
g = torch.randint(size=(3,2),low= 0, high=10)

In [105]:
print(f)

tensor([[8, 1, 2],
        [4, 9, 4]])


In [106]:
print((g))

tensor([[0, 9],
        [7, 5],
        [0, 6]])


In [107]:
# Matrix multiplication 

torch.matmul(f,g)

tensor([[  7,  89],
        [ 63, 105]])

In [108]:
# Dot product between two vectors

vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

In [109]:
torch.dot(vector1, vector2)

tensor(11)

In [112]:
## Transpose 


torch.transpose(f,0,1)

tensor([[8, 4],
        [1, 9],
        [2, 4]])

In [114]:
h  = torch.randint(size=(3,3),low=0, high= 10, dtype=torch.float32)
h

tensor([[7., 7., 8.],
        [8., 9., 6.],
        [2., 9., 4.]])

In [115]:
## Determinant

torch.det(h)

tensor(166.)

In [117]:
# Inverse

torch.inverse(h)

tensor([[-0.1084,  0.2651, -0.1807],
        [-0.1205,  0.0723,  0.1325],
        [ 0.3253, -0.2952,  0.0422]])

### Comparison Operations

In [118]:
i = torch.randint(size=(2,3),low= 0, high=10)
j = torch.randint(size=(2,3),low= 0, high=10)

In [120]:
print(i)

tensor([[5, 5, 3],
        [5, 0, 7]])


In [121]:
print(j)

tensor([[4, 7, 1],
        [3, 6, 9]])


In [122]:
# Greater than 

i > j

tensor([[ True, False,  True],
        [ True, False, False]])

In [123]:
# Less than 

i < j

tensor([[False,  True, False],
        [False,  True,  True]])

In [124]:
# Equal to

i == j

tensor([[False, False, False],
        [False, False, False]])

In [125]:
# Not equal to 

i != j

tensor([[True, True, True],
        [True, True, True]])

In [126]:
i >= j

tensor([[ True, False,  True],
        [ True, False, False]])

In [127]:
i<=j

tensor([[False,  True, False],
        [False,  True,  True]])

### Special Functions 

In [132]:
k = torch.randint(size=(2,3),low= 0, high=10, dtype = torch.float32)
k

tensor([[1., 3., 8.],
        [6., 7., 2.]])

In [129]:
## Log

torch.log(k)

tensor([[1.9459,   -inf, 0.0000],
        [  -inf, 2.0794, 1.6094]])

In [130]:
# Exponential 

torch.exp(k)

tensor([[1.0966e+03, 1.0000e+00, 2.7183e+00],
        [1.0000e+00, 2.9810e+03, 1.4841e+02]])

In [131]:
# Sigmoid 

torch.sigmoid(k)

tensor([[0.9991, 0.5000, 0.7311],
        [0.5000, 0.9997, 0.9933]])

In [136]:
# Softmax 

torch.softmax(k, dim =0)

tensor([[0.0067, 0.0180, 0.9975],
        [0.9933, 0.9820, 0.0025]])

In [137]:
# Relu 

torch.relu(k)

tensor([[1., 3., 8.],
        [6., 7., 2.]])

### Inplace operation

In [138]:
m = torch.rand(2,3)
n = torch.rand(2,3)

In [139]:
print(m)
print(n)

tensor([[0.1124, 0.3087, 0.9973],
        [0.4257, 0.6890, 0.9657]])
tensor([[0.0257, 0.4205, 0.0656],
        [0.4508, 0.0553, 0.3140]])


In [140]:
m + n

tensor([[0.1382, 0.7292, 1.0629],
        [0.8766, 0.7444, 1.2797]])

In [143]:
m.add_(n)

tensor([[0.1382, 0.7292, 1.0629],
        [0.8766, 0.7444, 1.2797]])

In [144]:
m

tensor([[0.1382, 0.7292, 1.0629],
        [0.8766, 0.7444, 1.2797]])

In [145]:
n

tensor([[0.0257, 0.4205, 0.0656],
        [0.4508, 0.0553, 0.3140]])

In [146]:
torch.relu(m)

tensor([[0.1382, 0.7292, 1.0629],
        [0.8766, 0.7444, 1.2797]])

In [147]:
m.relu_()

tensor([[0.1382, 0.7292, 1.0629],
        [0.8766, 0.7444, 1.2797]])

In [148]:
m

tensor([[0.1382, 0.7292, 1.0629],
        [0.8766, 0.7444, 1.2797]])

### Copying a Tensor 

In [149]:
a = torch.rand(2, 3)

In [150]:
a

tensor([[0.7460, 0.9357, 0.8925],
        [0.1370, 0.1803, 0.4023]])

In [151]:
b = a

In [152]:
b

tensor([[0.7460, 0.9357, 0.8925],
        [0.1370, 0.1803, 0.4023]])

In [156]:
# But, this above approach has a problem. Same memory location and if we change main tensor, copied tensor also will change 
a[0][0] = 0

In [154]:
a

tensor([[0.0000, 0.9357, 0.8925],
        [0.1370, 0.1803, 0.4023]])

In [155]:
b

tensor([[0.0000, 0.9357, 0.8925],
        [0.1370, 0.1803, 0.4023]])

In [157]:
id(a)

136377211132400

In [158]:
id(b)

136377211132400

In [159]:
# Solution 

b = a.clone()

In [160]:
a

tensor([[0.0000, 0.9357, 0.8925],
        [0.1370, 0.1803, 0.4023]])

In [161]:
b

tensor([[0.0000, 0.9357, 0.8925],
        [0.1370, 0.1803, 0.4023]])

In [165]:

a[0][0]=10
a

tensor([[10.0000,  0.9357,  0.8925],
        [ 0.1370,  0.1803,  0.4023]])

In [166]:
b

tensor([[0.0000, 0.9357, 0.8925],
        [0.1370, 0.1803, 0.4023]])

In [167]:
id(a)

136377211132400

In [168]:
id(b)

136377211184448

## Tensor Operations in GPU

In [169]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda')

In [171]:
# Creating a new tensor on GPU

torch.rand((2,3),device = device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [173]:
# Moving an existing tensor to GPU 

a = torch.rand(2,3)
a

tensor([[0.5392, 0.1580, 0.6420],
        [0.6931, 0.0031, 0.6751]])

In [174]:
a.to(device)

tensor([[0.5392, 0.1580, 0.6420],
        [0.6931, 0.0031, 0.6751]], device='cuda:0')

In [175]:
b = a.to(device)

In [176]:
b + 5

tensor([[5.5392, 5.1580, 5.6420],
        [5.6931, 5.0031, 5.6751]], device='cuda:0')

### Comparison time between CPU and GPU

In [179]:
import time 

size = 10000 # Large size for performance comparison 

matrix_cpu1 = torch.randn(size,size)
matrix_cpu2 = torch.randn(size,size)

start_time = time.time()
result_cpu  = torch.matmul(matrix_cpu1,matrix_cpu2)
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time:.4f}")

matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

start_time = time.time()
result_gpu  = torch.matmul(matrix_gpu1,matrix_gpu2)
torch.cuda.synchronize()
gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time:.4f}")

print('\n Speedup (CPU time/ GPU time):',cpu_time/gpu_time)

Time on CPU: 10.6621
Time on GPU: 0.3181

 Speedup (CPU time/ GPU time): 33.51744033097618


### Reshaping Tensors 


In [181]:
a = torch.ones(4,4)
a


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [182]:
#reshape
a.reshape(2,2,2,2)


tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [183]:
# flatten 

a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [184]:
# permute 

b = torch.rand(2,3,4)
b

tensor([[[0.2184, 0.5957, 0.0099, 0.1087],
         [0.4019, 0.2277, 0.1726, 0.1111],
         [0.0280, 0.5452, 0.1149, 0.2394]],

        [[0.0047, 0.9985, 0.5426, 0.5034],
         [0.0086, 0.3167, 0.0358, 0.8584],
         [0.5710, 0.0886, 0.0743, 0.1493]]])

In [185]:
b.permute(2,1,0)

tensor([[[0.2184, 0.0047],
         [0.4019, 0.0086],
         [0.0280, 0.5710]],

        [[0.5957, 0.9985],
         [0.2277, 0.3167],
         [0.5452, 0.0886]],

        [[0.0099, 0.5426],
         [0.1726, 0.0358],
         [0.1149, 0.0743]],

        [[0.1087, 0.5034],
         [0.1111, 0.8584],
         [0.2394, 0.1493]]])

In [186]:
b.permute(2,1,0).shape

torch.Size([4, 3, 2])

In [188]:
# unsqueeze 
#image size 
c = torch.rand(226, 226, 3)

In [191]:
c.unsqueeze(0).shape # to convert a single image into a batch 

torch.Size([1, 226, 226, 3])

In [192]:
#Squeeze 

d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

### Numpy and Pytorch

In [193]:
import numpy as np



In [194]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [195]:
b = a.numpy()

In [196]:
b

array([1, 2, 3])

In [197]:
type(b)

numpy.ndarray

In [198]:
type(a)

torch.Tensor

In [199]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [202]:
d = torch.from_numpy(c)

In [201]:
type(c)

numpy.ndarray

In [203]:
type(d)

torch.Tensor